// <auto-generated />
using System;
using System.Collections.Generic;
using BackendAPI.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20221212130634_AddCommandModels")]
    partial class AddCommandModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.Models.CommandGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfigurable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommandGroup", (string)null);
                });

            modelBuilder.Entity("BackendAPI.Models.CommandParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubCommandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubCommandId");

                    b.ToTable("CommandParameter", (string)null);
                });

            modelBuilder.Entity("BackendAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<List<string>>("MessageIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("BackendAPI.Models.EventVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("DiscordUserIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventVote", (string)null);
                });

            modelBuilder.Entity("BackendAPI.Models.Magic8BallResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Magic8BallResponse", (string)null);
                });

            modelBuilder.Entity("BackendAPI.Models.SubCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommandGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExampleMediaUrl")
                        .HasColumnType("text");

                    b.Property<string>("ExampleText")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommandGroupId");

                    b.ToTable("SubCommand", (string)null);
                });

            modelBuilder.Entity("BackendAPI.Models.CommandParameter", b =>
                {
                    b.HasOne("BackendAPI.Models.SubCommand", null)
                        .WithMany("Parameters")
                        .HasForeignKey("SubCommandId");
                });

            modelBuilder.Entity("BackendAPI.Models.EventVote", b =>
                {
                    b.HasOne("BackendAPI.Models.Event", null)
                        .WithMany("Votes")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("BackendAPI.Models.SubCommand", b =>
                {
                    b.HasOne("BackendAPI.Models.CommandGroup", null)
                        .WithMany("SubCommands")
                        .HasForeignKey("CommandGroupId");
                });

            modelBuilder.Entity("BackendAPI.Models.CommandGroup", b =>
                {
                    b.Navigation("SubCommands");
                });

            modelBuilder.Entity("BackendAPI.Models.Event", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("BackendAPI.Models.SubCommand", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
